CREATE TABLE `links` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(4096) NULL DEFAULT NULL,
    `type` VARCHAR(20) NULL DEFAULT NULL,
    `data` MEDIUMTEXT NULL,
    `count` INT(10) UNSIGNED NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;
