CREATE TABLE `links` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(4096) NULL DEFAULT NULL,
    `type` VARCHAR(20) NULL DEFAULT NULL,
    `data` MEDIUMTEXT NULL,
    `cnt` INT(10) UNSIGNED NULL DEFAULT NULL,
    `text` VARCHAR(500) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
